baseurl = "https://tdu-isl.github.io/home/research/azure-sec" # 後ほどGitHub Pagesの設定ができたらこちらを修正します。
languageCode = "ja"
defaultContentLanguage = "ja"
title = "SkytechLab_BLOG"
theme = "hugo-theme-bootstrap"



[params]
