baseurl = "https://yoitsu1838.github.io/hugo-isl-ms-staticPreview/" # 後ほどGitHub Pagesの設定ができたらこちらを修正します。
languageCode = "ja"
defaultContentLanguage = "ja"
title = "SkytechLab_BLOG"
theme = "hugo-theme-bootstrap"



[params]
