baseURL = "https://yoitsu1838.github.io/home/research/azure-sec"
logoHomeLink = "/home/research/azure-sec"
title = "SkytechLab_BLOG"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2021 SkytechLab. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true # If you use only one language comment this option
#disableLanguages = ["fr", "zh-cn" ,"zh-tw"] # For disable one or more language

# Pagination
paginate = 5
# paginatePath = "page"

# Disqus
# disqusShortname = ""

# Google analytics
# googleAnalytics = ""

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
